{{- if and .Values.istio.enabled .Values.istio.ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}-gw
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.ingress.managementHostName }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  hosts:
  - {{ .Values.istio.ingress.managementHostName | quote }}
  gateways:
  - {{ template "rabbitmq-ha.fullname" . }}-gw
  http:
  - route:
    - destination:
        host: {{ template "rabbitmq-ha.fullname" . }}-internal.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.rabbitmqManagerPort }}
{{- end }}