{{- if or .Values.rabbitmqAmqpsSupport.enabled (and .Values.prometheus.exporter.enabled .Values.prometheus.exporter.exportOperator) }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations_lb }}
  annotations:
{{ toYaml .Values.service.annotations_lb | indent 4 }}
{{- end }}
  name: {{ template "rabbitmq-ha.fullname" . }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    {{- if .Values.rabbitmqAmqpsSupport.enabled }}
    - name: amqps
      protocol: TCP
      port: {{ .Values.rabbitmqAmqpsSupport.amqpsNodePort }}
      targetPort: amqps
    {{- end }}
    {{ if and .Values.prometheus.exporter.enabled .Values.prometheus.exporter.exportOperator }}
    - name: exporter
      protocol: TCP
      port: {{ .Values.prometheus.exporter.port }}
      targetPort: exporter
    {{ end }}
  selector:
    app: {{ template "rabbitmq-ha.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- end }}